#-------------------------------
# Site Settings
title: Bike Adventure Italy
logo: '/images/logo/logo.png' 
description: Scopri i migliori tracciati ciclistici dell'Italia, immergiti nella cultura locale e unisciti alla nostra comunità appassionata.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bikeadventureitaly.it" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  author__name: Pacs Brothers
  author__bio: IT, DIY and bike lover.
  author__avatar: '/images/logo/logo.png'

social:
- {icon: "logo-youtube", link: "https://www.youtube.com/@PacsRiders"}
- {icon: "logo-linkedin", link: "https://www.linkedin.com/in/mattia-pacchin-255802167/"}
- {icon: "logo-facebook", link: "https://www.facebook.com/Pacchinmattia"}
- {icon: "logo-instagram", link: "https://www.instagram.com/mattiapacchin/"}


#-------------------------------
# Newsletter
#mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
#mailchimp__identifier:  dataumbrella.substack.com/ # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#mailchimp__input__text: Subscribe here
#mailchimp__button__text: Subscribe to our newsletter


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'baldo2'
      url: '/images/social/baldo2.png'
    - alt: 'baldo3'
      url: '/images/social/baldo3.png'
    - alt: 'bici_asolo'
      url: '/images/social/bici_asolo.png'
    - alt: 'elba1'
      url: '/images/social/elba1.png'
    - alt: 'elba2'
      url: '/images/social/elba2.png'
    - alt: 'elba4'
      url: '/images/social/elba4.png'
    - alt: 'lessinia1'
      url: '/images/social/lessinia1.png'
    - alt: 'lessinia2'
      url: '/images/social/lessinia2.png'
    - alt: 'recoaro1'
      url: '/images/social/recoaro1.png'


#-------------------------------
# Contact Settings
#contact:
#  email: https://formspree.io/f/mgerdblk # Add your email for contant form
#  description: 

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: G-FG5QXJ66YZ # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
